### ISSUE TITLE
Editor not saving all code

### ISSUE THREAD

**Issue by neil-ptr** [onflow/flow-playground#287] opened 2022-08-04 21:02 UTC
**Describe the bug**
When quickly typing out code on an account or transaction and then switching to a different account or transaction and then coming back, sometimes there are pieces near the end of the code that are missing

**To Reproduce**
Follow steps 1-5 in https://github.com/onflow/flow-playground/issues/286
6. On the transaction, delete everything and quickly type out `import BasicToken from 0x01` and switch to account 1
7. come back to the transaction you just edited and there should be code missing
8. Might need to repeat 6 and 7 since the issue is inconsistent on when it happens

**Expected behavior**

**Desktop (please complete the following information):**
OS: MacOS
Browser: Chrome
Version Version 103.0.5060.134 (Official Build) (x86_64)

**Additional context**
- Only seems to appear in production (could not reproduce locally) and a part of the solution might be related to https://github.com/onflow/flow-playground/issues/284
- related https://github.com/onflow/flow-playground/issues/260

**Comment by alse** [comment] 2022-08-19 22:39
I was able to reproduce this by throttling the network to Slow 3G. Here are the main issues:

- Slow network connections can delay the transaction mutations. This is compounded by the lack of mutation debouncing and auto-refetching associated queries
- The Monaco editor does not stay in sync with the Apollo cache. Clicking away and returning to the transactions view will load a stale value from the cache, and the editor's value won't be updated as the mutations resolve
- When a code editor view loads, the Monaco setup triggers a mutation. If the cache is stale due to pending mutations, this will persist the stale value to the db

Debouncing mutations and optimistic cache updates would help, but network delays could still cause problems. Is disabling auto-save an option?

**Comment by devbugging** [comment] 2022-08-22 19:45
I don't think autosaving would be an option, but we could potentially change autosave logic, maybe only save when the editor loses focus? The problem is only if that will work when the focus is lost due to the click on "send transaction" or similar.

**Comment by alse** [comment] 2022-09-15 20:28
Fixed by #302

**Closed as completed by alse** 2022-09-15 20:28 UTC
Labels: Bug
