### ISSUE TITLE
Flow playground broken during deployment

### ISSUE THREAD

**Issue by YuansongFeng** [onflow/flow-playground#186] opened 2021-11-12 01:02 UTC
I am following the Flow tutorial on (https://docs.onflow.org/cadence/tutorial/04-non-fungible-tokens/) and try to deploy NFT contract in (https://play.onflow.org/b60aa97d-d030-476e-9490-24f3a6f90161?type=account&id=0). However when I hit 'Deploy' the page goes blank. 

Could anyone help take a look? This should be reproducible by anyone. Thank you!

**Comment by hichana** [comment] 2021-11-15 23:53
Pulling latest from upstream master branch and running locally I somehow cannot manage to reproduce this issue. However the play.onflow.org deployment indeed has the issue. Still looking digging around, tho I believe I know where the issue might originate. I'm not sure if deploying a fix to where the issue originates would be appropriate if I can't reproduce locally and confirm definitively that the change I make resolves the issue.

**Comment by hichana** [comment] 2021-11-16 00:07
screenshot of running locally and deploying the NFT contract:
<img width="1440" alt="Screen Shot 2021-11-16 at 9 06 43 AM" src="https://user-images.githubusercontent.com/8943047/141872022-7d5bf50d-ecae-4aea-949c-1448acf40174.png">

**Comment by hichana** [comment] 2021-11-16 00:40
It appears that the NFT tutorial example simply needs to be re-created to mitigate some conflict with the latest version of the playground. I did so here:

https://play.onflow.org/039d4a79-d742-436a-b030-4f566d49c1dc?type=account&id=0

That playground instance works as expected. @YuansongFeng could you try that link and confirm that it works for you?

I am pretty sure is due to how the initial state string is handled. I'm going to start working on this now. I believe it's that old/existing projects have the state initialized with an empty string, yet the way I've set up the new resources explorer was to expect a string with empty brackets in it, ex.'{}' . I'm pretty sure that this change is what is causing the error, and to fix it would mean a small refactor of how this is handled.

**Comment by hichana** [comment] 2021-11-16 03:58
PR #187 updates the links in `Examples.tsx`, which once merged and deployed will resolve the issue described here. The underlying issue may still persist tho, effecting already-created playgrounds. I created issue #188 to document this.

**Comment by hichana** [comment] 2021-11-16 12:24
@turbolent is there a way to prioritize thePR I made so new users coming to the playground and using the tutorials can deploy and fork? I believe the new playground links I created work but it would of course need confirmation from someone on your side. Thank you

**Comment by joshuahannan** [comment] 2021-11-16 23:12
I've given the PR a review. Thanks for submitting! Once we get my suggestions fixed we can merge it

**Closed** 2021-11-18 18:17 UTC
Labels: Bug
