### ISSUE TITLE
Control panel deploy contract to a single user flow

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#359] opened 2022-09-29 02:56 UTC
Is your feature request related to a problem? Please describe.
v2 Playground mvp needs to have functionality to deploy contracts to users. 

Describe the solution you'd like
- add feature to control panel component to show label to indicate you can choose one user to send.
- scenario 1: if user is deploying to **one** account **and** has **one** account selected in the control panel, label will read `deploying to 1 of 1 account(s)` 
- scenario 2:if user is deploying to **three** accounts **and** has **two** accounts selected in the control panel, label will read `deploying to 2 of 3 account(s)` 

todo ask @srinjoyc about multiple account contract deployment priority

**Comment by fotescodev** [comment] 2022-11-15 18:41
Duplicate of another ticket that has been completed - @fotescodev to find the ticket and reference

**Closed as completed** 2022-11-15 18:42 UTC
Labels: V2, mvp
