### ISSUE TITLE
Problem loading projects & maximum number of 10 projects reached

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-playground#617] opened 2023-04-03 23:09 UTC
**Describe the bug**
I'm unable to do anything on playground v2. I get the following error displayed at the bottom of the screen 

<img width="590" alt="Screenshot 2023-04-03 at 6 04 13 PM" src="https://user-images.githubusercontent.com/108043524/229645253-abdda440-dd41-4e57-bafb-ca65436e1580.png">

And loading my projects fails, leaving me unable to delete any projects.

<img width="687" alt="Screenshot 2023-04-03 at 6 05 27 PM" src="https://user-images.githubusercontent.com/108043524/229645401-fd5da1fc-7c72-455e-921f-34ff3cd6a02e.png">

It's noteworthy that I have only been using playground v1 thus far.

**To Reproduce**

For me, I only have to go to playground for the error to occur. I'm assuming this is due to previous projects cached in my browser, as I don't have the problem in incognito or other browser windows.

**Expected behavior**
Ability to write Cadence, deploy contracts, execute scripts & send transactions.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Browser - 111.0.5563.64 (Official Build) (arm64) | OS - Ventura 13.2.1

**Comment by bluesign** [comment] 2023-04-04 12:18
+1

**Comment by bthaile** [comment] 2023-04-04 15:04
@sisyphusSmiling 
Can you try again, we had backend database deployment issues that didn't allow migration of previous user sessions.

**Comment by sisyphusSmiling** [comment] 2023-04-04 16:29
@bthaile still having the issue

**Comment by DylanTinianov** [comment] 2023-04-05 20:12
Sorry for your frustrations, I will be looking into this issue asap! Closing this issue since it's a duplicate of https://github.com/onflow/flow-playground/issues/626

**Closed as completed by DylanTinianov** 2023-04-05 20:12 UTC
Labels: Bug
