### ISSUE TITLE
Add a `flow.json` file on export of a playground project

### ISSUE THREAD

**Issue by srinjoyc** [onflow/flow-playground#225] opened 2022-02-10 15:34 UTC
**Is your feature request related to a problem? Please describe.**
When exporting playground projects, we should supply a flow.json with arbitrary keys on accounts that can be immediately used with the emulator locally. This would make it much easier to go from experimentation on the limited playground features to a local environment to continue building. The goal would be to have minimal friction and configuration between playground and emulator + CLI and have the contracts, scripts, and transactions work out of the box. 

**Describe the solution you'd like**
Each account should have a set of keys.
We should replace the cadence imports with appropriate aliases/relative paths so the scripts can be run.
Contracts should be easy to deploy and scripts and transactions should work without further modification.

**Comment by srinjoyc** [comment] 2022-02-25 16:24
We could try exporting a bash/shell script to run the initial account setup @MaxStalker

**Comment by MaxStalker** [comment] 2022-05-05 15:17
I started the work on implementation via shell scripts, but atm it's stalled in favor of https://github.com/onflow/flow-playground/issues/251 - which affects more users and should be fixed right away.

**Comment by kerrywei** [comment] 2022-05-09 13:51
Per confirmed with Max -- this task can be handed over

**Comment by srinjoyc** [comment] 2022-05-20 15:21
Add a readme with a project export for instructions

**Comment by bthaile** [comment] 2023-04-27 16:48
not going to add flow.json
cli can generate one for an exported playground project. closing

**Comment by bartolomej** [comment] 2023-08-19 10:44
I wonder if the export feature could be adapted so that instead of downloading the exported project in the browser, the `flow setup` command could be used to scaffold a project given a flow playground URL.

Obviously, this would some changes on the Flow CLI side (e.g. adding a separate `flow setup --playground <URL>` flag or detecting the type of scaffold and then implementing the exporting logic).

But I imagine having a consolidated way of setting up / scaffolding new projects would contribute towards a better DX. Plus this could also solve the issue of generating `flow.json` file, since I believe Flow CLI could do that easily during the scaffolding process.

**Closed** 2024-01-22 18:14 UTC
Labels: Feature
