### ISSUE TITLE
Support Safari 

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-playground#618] opened 2023-04-04 12:21 UTC
**Describe the bug**
It does not work in safari

**To Reproduce**
try to run with safari

**Expected behavior**
should work in safari 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser safari
 - Version Version 16.4 (18615.1.26.11.22)

**Additional context**
it is 2023 and I use playground a lot on iPad

**Comment by bluesign** [comment] 2023-04-04 14:26
Safari problem turned out to be ITP, it can be fixed by moving api to first party. ( simple nginx config should suffice ) 

I made a poc at https://safariplay.dnz.dev/

**Comment by DylanTinianov** [comment] 2023-04-05 20:07
Duplicate of https://github.com/onflow/flow-playground/issues/631

**Closed as completed by DylanTinianov** 2023-04-05 20:07 UTC
