### ISSUE TITLE
Deploying contract with init storage does not show storage container

### ISSUE THREAD

**Issue by timongll** [onflow/flow-playground#158] opened 2021-07-17 08:45 UTC
When deploying a contract with a storage initialized, storage container does not show.
<img width="745" alt="Screen Shot 2021-07-16 at 6 53 03 PM" src="https://user-images.githubusercontent.com/25440724/126031526-ed83d2c4-2d60-4312-bf15-91c075ff45ad.png">

**To Reproduce**
https://play.onflow.org/3a0ea2eb-f827-440e-a03f-13bb411e1518?type=account&id=ff3530f4-306d-4c0b-9c28-fe3e00691e71

Deploy 0x01 then 0x02, Flow Vault does not show on 0x02. 

Execute transaction "Initialize Flow vaults" with 0x01, 0x02, 0x03, 0x04, 0x05 as params. 0x01, 0x03, 0x04, 0x05 show storage, 0x02 does not.

**Comment by bluesign** [comment] 2021-07-17 09:50
@10thfloor, This one is tricky, I checked not much but I think the problem is because the contract is not active in the transaction it is deployed. When you get the delta register changes, resource variables referencing new contract are not resolving.

**Comment by ic3guy** [comment] 2021-09-29 05:52
I'll just add that this bug impacts the "Hello World" cadence tutorial. In the "Creating a Resource" section it says we should be able to see a resource after deploy, but it does not show in the UI as described above.

**Closed** 2022-09-16 10:18 UTC
Labels: Bug
