### ISSUE TITLE
Excessive Errors

### ISSUE THREAD

**Issue by neil-ptr** [onflow/flow-playground#285] opened 2022-08-03 20:02 UTC
**Describe the bug**
Typing out some variables on the playground shows excessive errors

**To Reproduce**
1. Go to the playground and open up account 1
2. Type out the following at the bottom of the contract: 
    ```
        access(all) fun hi(): String {
    ```
3. First 5 errors should appear
![Screen Shot 2022-08-03 at 1 57 29 PM](https://user-images.githubusercontent.com/46465568/182698012-eea45964-9c4f-4e1c-b833-98e1161bb915.png)

**Expected behavior**
Only last error on the above image should appear

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.5
 - Browser Chrome
 - Version 103.0.5060.134 (Official Build) (x86_64)

**Additional context**
* Related to: https://axiomzen.slack.com/archives/C03FUAG6SEP/p1652809839024079
* Related https://github.com/onflow/flow-playground/issues/260

**Comment by devbugging** [comment] 2022-08-12 15:43
We should do discovery on how to fine-tune the frequency of code checks. The checks of the code should be less common. We need to take a look how other IDEs handle this (for example only check after a word is completed etc). We should also check the support for that by the code editor itself.

**Comment by alse** [comment] 2022-08-29 22:43
Excessive errors caused by the frontend are fixed in onflow/cadence#288. A possible LS issue with duplicate errors is tracked in https://github.com/onflow/cadence-tools/issues/36

**Closed as completed** 2022-09-15 21:05 UTC
Labels: Bug
