### ISSUE TITLE
"Oops! Something went wrong. If you'd like, please report the Bug. Thank you!"

### ISSUE THREAD

**Issue by Disha1998** [onflow/flow-playground#708] opened 2023-06-19 09:02 UTC
![Screenshot 2023-06-19 at 2 31 55 PM](https://github.com/onflow/flow-playground/assets/69969675/3643d091-5ec7-42e4-aab6-c73dce190085)

## During deployment of contract-4 getting this issue, could anyone please help me to solve that!

**Comment by muttoni** [comment] 2023-06-19 12:23
I can reproduce as well. 

Steps to reproduce:

Follow this playground link: https://play.flow.com/3585af61-11ce-42fc-bfc5-c2aa774d394e?type=contract&id=7cbf8260-cb1d-4fe2-a787-9fc6cb4541e9

Deploy contracts in order (from 1 to 4) -> on 4th one, there will be this issue "Oops! Something went wrong."

Console output:

<img width="498" alt="image" src="https://github.com/onflow/flow-playground/assets/27052451/52b226cf-1c5d-4700-a381-0f0a54ea06b4">

**Comment by nialexsan** [comment] 2023-06-19 13:35
from the logs I see that it errors in `Contract 4` on this line:
```
init(adminAccount: AuthAccount) {
```

> transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
> error: invalid argument count, too few arguments: expected 1, got 0, next missing argument: `AuthAccount`

**Comment by jribbink** [comment] 2023-06-19 14:04
I don't think the playground supports passing an AuthAccount as a parameter.

duplicate of https://github.com/onflow/flow-playground/issues/690

**Comment by fotescodev** [comment] 2023-06-19 14:13
Ok, let's add a proper error message.

**Comment by bluesign** [comment] 2023-06-20 14:25
maybe will be better we update the FlowToken contract ? It is a core contract

**Closed as completed** 2023-06-26 16:41 UTC
